variables:
  
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - "\"`cygpath \"$VS100COMNTOOLS\\vsvars32.bat\"`\""

stages:
  - build
  - deploy


build:
  stage: build
  tags:
    - hcloud
  script:
    - 'echo "Release build..."'
    - 'msbuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet SRO_DevKit.sln'
  artifacts:
    untracked: false
    paths:
      - BinOut/

deploy:
  stage: deploy
  tags:
    - hcloud
  dependencies:
    - build
  script:
    - echo "Deploying is not implemented yet"
  only:
    - stable