variables:
  
before_script:
  - echo "Preparing environment ..."
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - "call \"%VS100COMNTOOLS%\\vsvars32.bat\""
  - echo "Perparation done."

stages:
  - build

build:
  stage: build
  tags:
    - vs2005
    - vs2010
    - windows
  script:
    - 'echo "Release build..."'
    - 'msbuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet SRO_DevKit.sln'
  artifacts:
    untracked: true

