variables:
  PROJECT_NAME: "SRO_DevKit"
before_script:
  - echo "starting build for %PROJECT_NAME%"
  - "%VS100COMNTOOLS%\vsvars32.bat"
stages:
  - build

build:
  stage: build
  script:
  - echo "Release build..."
  - '"msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%.sln"'
  artifacts:
    untracked: true
