variables:
  
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - windows
    - cygwin
  script:
    - cd helpers
    - chmod +x make_project_nmake.cmd make_project_nmake_build.cmd
    - ./make_project_nmake.cmd
    - ./make_project_nmake_build.cmd
  artifacts:
    untracked: false
    paths:
      - BinOut/

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying is not implemented yet"
  only:
    - stable