variables:
  registry: registry.gitlab.com/florian0/sro_devkit
  

stages:
  - build
  - deploy
  - docs

docker_doxygen:
  stage: build
  variables:
    name: doxygen
  image: dind
  script:
    - docker info
    - docker build -t "${registry}:${name}" docker/${name}/
    - echo $REGISTRY_PASSWORD | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push -t "${registry}:${name}"
  only:
    - docker

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  tags:
    - windows
    - cygwin
  script:
    - cd helpers
    - chmod +x make_project_nmake.cmd make_project_nmake_build.cmd
    - ./make_project_nmake.cmd
    - ./make_project_nmake_build.cmd
  artifacts:
    untracked: false
    paths:
      - BinOut/
    expire_in: 1 day
